### ISSUE TITLE
Point System

### ISSUE THREAD

**Issue by dbaledio** [dbaledio/comp129-resurrection#3]
Objective: Implement a point system that grows and shrinks according to the resources consumed or the sprites killed. The score value will be shown on the scoreboard.
Approach: Will add new methods to track the score. Will introduce a new class to hold the score board.
Classes: 
    Player.java - Add private variables to track the user's score, add methods for manipulating the score value
    Character.java - Will effect Collision method by adding logic to determine if the colliding object is a resource, therefore adding a certain value to the score. If the player's sprite is being attacked, the score will drop as the size drops.
    MainApplication.java - Will have to add a ScoreBoard object to the screen upon booting into a game.
    <NEW> ScoreBoard.java - Will be nested under Map or CircleBrawl folder. Will be a combination of GObjects. Will have to update quickly, so I will have to investigate using this with the game tick.
Complexity: Medium

**Comment by onzfonz** [comment]
Let's have you do this, with the added wrinkle of saving the score to a file so that it can persist on disk between running the application.  Let me know if you have any questions.

**Comment by dbaledio** [comment]
To test the feature:
1. Pull from repository
    1.a. Headphone users beware, lower the volume. Or better, mute it.
2. Run MainApplication
3. Select Single Player
4. Notice the score box in the upper right-hand corner
    4.a. Notice it is prepopulated with a score, which was loaded from a file
    4.b. Notice it grows and shrinks in relation to your character
5. Select Menu in bottom-right corner
6. Select Quit
7. Repeat steps 1 - 3
8. Notice the last score upon exit is reloaded
